baseURL = "/"
# canonifyURLs = true
defaultContentLanguage = "en"
# disableLanguages = ["ua"]
paginate = "6"
relativeURLs = true
summaryLength = "50"
title = "Epicurus - Главная"
# [Languages.en]
# contentDir = "content/en"
# home = "Home"
# languageCode = "en-us"
# languageName = "En"
# weight = 3
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2
[Languages.ua]
contentDir = "content/ua"
home = "Головна"
languageCode = "ua"
languageName = "Укр"
weight = 3
[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en"
languageName = "ENG"
weight = 1

# [Languages.ua.params.form]
# action = "#"
# enable = true
# method = "POST"

# [[Languages.ua.params.form.field]]
# enable = true
# name = "name"
# placeholder = "**\\*** Ім`я"
# required = ""
# type = "text"

# [[Languages.ua.params.form.field]]
# enable = true
# name = "tel"
# placeholder = "+38 (0__) ___ - __ - __"
# label = "Телефон"
# required = ""
# type = "tel"

# [[Languages.ua.params.form.field]]
# enable = true
# placeholder = "Надіслати"
# type = "submit"


[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true

[params]
CIO_site_id = "XXX"
GTM = "GTM-WHBQ3BV"
develop = "Anastasiia_Berest"
author = "Epicurus"

logo = "images/logo.svg"
logo_sm = "images/logo-sm.svg"
logo_w = "116"

site_name = "epicurus"
site_url = "#"

description = "An innovative platform for investors, people, enthusiasts"

# [[params.plugins.js]]
# link = "plugins/js/jquery.min.js"
# [[params.plugins.js]]
# link = "plugins/js/bootstrap.bundle.min.js"

[taxonomies]
category = "categories"
tag = "tags"


[params.preloader]
enable = true
preloader = ""

############################# socials #################################
[[params.social]]
label = "fb"
title = "Facebook"
link = "https://www.facebook.com/InternationalTradeGroup2018"
icon_sm = "fb"

[[params.social]]
label = "im"
title = "Instagram"
link = "https://www.instagram.com/itg_official__/"
icon_sm = "im"

[[params.social]]
label = "ytb"
title = "YouTube"
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"
icon = "youtube" 
icon_sm = "ytb"

[[params.social]]
label = "ln"
title = "LinledIn"
link = "https://www.linkedin.com/in/international-trade-group"
icon = "linkedin" 
icon_sm = "ln"

############################# footer #################################
[params.footer]
    copyright = "Epicurus &copy; 2023 All Rights Reserved"
    copyright_text = "Multifunctional platform, your one-stop tool. Created specifically for investors and traders who strive to achieve financial success."

[[params.nav]]
    title = "Home"
    URL = "/"
[[params.nav]]
    title = "About Us"
    URL = "/"
[[params.nav]]
    title = "Blogs"
    URL = "/"
[[params.nav]]
    title = "Products"
    URL = "/"


[[menu.footer]]
name = "Company"
weight = 1
identifier = "company"
hasChildren = true 
    [[menu.footer]]
    parent = "company"
    name = "About us"
    URL = "/"
    weight = 1
    [[menu.footer]]
    parent = "company"
    name = "Careers"
    URL = "/"
    weight = 2
    [[menu.footer]]
    parent = "company"
    name = "Our Brand"
    URL = "/"
    weight = 3
    [[menu.footer]]
    parent = "company"
    name = "News"
    URL = "/"
    weight = 4
[[menu.footer]]
name = "Ecosystem"
weight = 2
identifier = "ecosystem"
hasChildren = true 
    [[menu.footer]]
    parent = "ecosystem"
    name = "Roadmap"
    URL = "/"
    weight = 1
    [[menu.footer]]
    parent = "ecosystem"
    name = "For Investors"
    URL = "/"
    weight = 2
    [[menu.footer]]
    parent = "ecosystem"
    name = "Business Angel"
    URL = "/"
    weight = 3
    [[menu.footer]]
    parent = "ecosystem"
    name = "Partners"
    URL = "/"
    weight = 4


[[menu.footer]]
name = "Products"
weight = 3
identifier = "products"
hasChildren = true 
    [[menu.footer]]
    parent = "products"
    name = "Robotic Trading"
    URL = "/"
    weight = 1
    [[menu.footer]]
    parent = "products"
    name = "Trust Management"
    URL = "/"
    weight = 2
    [[menu.footer]]
    parent = "products"
    name = "Deposit"
    URL = "/"
    weight = 3
    [[menu.footer]]
    parent = "products"
    name = "Academy"
    URL = "/"
    weight = 4




[[menu.footer]]
name = "Documentation"
weight = 4
identifier = "documentation"
hasChildren = true 
    [[menu.footer]]
    parent = "documentation"
    name = "Terms and Conditions"
    URL = "/"
    weight = 1
    [[menu.footer]]
    parent = "documentation"
    name = "Privacy Policy"
    URL = "/"
    weight = 2
    [[menu.footer]]
    parent = "documentation"
    name = "Terms of use"
    URL = "/"
    weight = 3
    [[menu.footer]]
    parent = "documentation"
    name = "AML Policy"
    URL = "/"
    weight = 4
    [[menu.footer]]
    parent = "documentation"
    name = "Cookie Policy"
    URL = "/"
    weight = 5
    [[menu.footer]]
    parent = "documentation"
    name = "Risk Warnings"
    URL = "/"
    weight = 6

