baseURL = "/"
# canonifyURLs = true
defaultContentLanguage = "en"
# disableLanguages = ["ua"]
paginate = 6
relativeURLs = true
summaryLength = "50"
title = "Epicurus - Главная"
# [Languages.en]
# contentDir = "content/en"
# home = "Home"
# languageCode = "en-us"
# languageName = "En"
# weight = 3
[Languages.ru]
contentDir = "content/ru"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 2
[Languages.ua]
contentDir = "content/ua"
home = "Головна"
languageCode = "ua"
languageName = "Укр"
weight = 3
[Languages.en]
contentDir = "content/en"
home = "Home"
languageCode = "en"
languageName = "ENG"
weight = 1

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

# [Languages.ua.params.form]
# action = "#"
# enable = true
# method = "POST"

# [[Languages.ua.params.form.field]]
# enable = true
# name = "name"
# placeholder = "**\\*** Ім`я"
# required = ""
# type = "text"

# [[Languages.ua.params.form.field]]
# enable = true
# name = "tel"
# placeholder = "+38 (0__) ___ - __ - __"
# label = "Телефон"
# required = ""
# type = "tel"

# [[Languages.ua.params.form.field]]
# enable = true
# placeholder = "Надіслати"
# type = "submit"


[outputs]
home = ["HTML", "RSS", "JSON"]
[sitemap]
ChangeFreq = "daily"
Priority = 0.6
Weight = [["main", "1"], ["sub2", "0.8"], ["sub3", "0.6"]]
enableRobotsTXT = true

[params]
GTM = "GTM-WHBQ3BV"
develop = "Anastasiia_Berest"
author = "Epicurus"

logo = "images/logo.svg"
logo_sm = "images/logo-sm.svg"
logo_w = "116"

site_name = "epicurus.io"
site_url = "#"

description = "An innovative platform for investors, people, enthusiasts"

[[params.plugins.js]]
link = "plugins/js/fancybox/fancybox.js"
[[params.plugins.css]]
link = "plugins/js/fancybox/fancybox.css"
[[params.plugins.js]]
link = "plugins/js/slider/splide.min.js"
[[params.plugins.css]]
link = "plugins/js/slider/splide.min.css"

[taxonomies]
category = "categories"
tag = "tags"


[params.preloader]
enable = true
preloader = ""

############################# socials #################################
[[params.social]]
label = "fb"
title = "Facebook"
link = "https://www.facebook.com/InternationalTradeGroup2018"
icon_sm = "fb"

[[params.social]]
label = "im"
title = "Instagram"
link = "https://www.instagram.com/itg_official__/"
icon_sm = "im"

[[params.social]]
label = "ytb"
title = "YouTube"
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"
icon = "youtube" 
icon_sm = "ytb"

[[params.social]]
label = "ln"
title = "LinledIn"
link = "https://www.linkedin.com/in/international-trade-group"
icon = "linkedin" 
icon_sm = "ln"


[[params.share]]
label = "fb"
title = "Facebook"
link = "https://www.facebook.com/sharer/sharer.php?u=" 
icon_sm = "fb"

[[params.share]]
label = "tw"
title = "Twitter"
link = "https://twitter.com/intent/tweet?text=" 
icon_sm = "tw"

[[params.share]]
label = "tm"
title = "Telegram"
link = "https://t.me/share/url?url=" 
icon_sm = "tm"

############################# footer #################################
[params.footer]
    copyright = "Epicurus &copy; 2023 All Rights Reserved"
    copyright_text = "Multifunctional platform, your one-stop tool. Created specifically for investors and traders who strive to achieve financial success."

# main menu
[[menu.main]]
URL = "/about-us"
name = "About Us"
weight = 1

[[menu.main]]
URL = "/news"
name = "Blogs"
weight = 2

[[menu.main]]
name = "Products"
url = "/products"
weight = 3
identifier = "products"

[[menu.main]]
name = "Robotic Trading"
parent = "products"
url = "/robotic-trading"
weight = 1
[[menu.main]]
name = "Trust Management"
parent = "products"
url = "/trust-management"
weight = 2
[[menu.main]]
name = "Epicurus Deposits"
parent = "products"
url = "/epicurus-deposits"
weight = 3
[[menu.main]]
name = "Academy"
parent = "products"
url = "/academy"
weight = 4

[[params.nav]]
    title = "Home"
    URL = "/"
[[params.nav]]
    title = "About Us"
    URL = "/about-us"
[[params.nav]]
    title = "Blogs"
    URL = "/news"
[[params.nav]]
    title = "Products"
    URL = "/products"

[[menu.footer]]
name = "Company"
weight = 1
identifier = "company"
hasChildren = true 
    [[menu.footer]]
    parent = "company"
    name = "About us"
    URL = "/about-us"
    weight = 1
    [[menu.footer]]
    parent = "company"
    name = "Careers"
    URL = "/careers"
    weight = 2
    [[menu.footer]]
    parent = "company"
    name = "Our Brand"
    URL = "/our-brands"
    weight = 3
    [[menu.footer]]
    parent = "company"
    name = "News"
    URL = "/news"
    weight = 4

[[menu.footer]]
name = "Ecosystem"
weight = 2
identifier = "ecosystem"
hasChildren = true 
    [[menu.footer]]
    parent = "ecosystem"
    name = "Roadmap"
    URL = "/roadmap"
    weight = 1
    [[menu.footer]]
    parent = "ecosystem"
    name = "For Investors"
    URL = "/for-investors"
    weight = 2
    [[menu.footer]]
    parent = "ecosystem"
    name = "Business Angel"
    URL = "/business-angel"
    weight = 3
    [[menu.footer]]
    parent = "ecosystem"
    name = "Partners"
    URL = "/partners"
    weight = 4

[[menu.footer]]
name = "Products"
weight = 3
identifier = "products"
hasChildren = true 
    [[menu.footer]]
    parent = "products"
    name = "Robotic Trading"
    URL = "/robotic-trading"
    weight = 1
    [[menu.footer]]
    parent = "products"
    name = "Trust Management"
    URL = "/trust-management"
    weight = 2
    [[menu.footer]]
    parent = "products"
    name = "Deposit"
    URL = "/deposit"
    weight = 3
    [[menu.footer]]
    parent = "products"
    name = "Academy"
    URL = "/academy"
    weight = 4

[[menu.footer]]
name = "Documentation"
weight = 4
identifier = "documentation"
hasChildren = true 
    [[menu.footer]]
    parent = "documentation"
    name = "Terms and Conditions"
    URL = "/terms"
    weight = 1
    [[menu.footer]]
    parent = "documentation"
    name = "Privacy Policy"
    URL = "/policy"
    weight = 2
    [[menu.footer]]
    parent = "documentation"
    name = "Terms of use"
    URL = "/terms-of-use"
    weight = 3
    [[menu.footer]]
    parent = "documentation"
    name = "AML Policy"
    URL = "/aml-policy"
    weight = 4
    [[menu.footer]]
    parent = "documentation"
    name = "Cookie Policy"
    URL = "/cookie-policy"
    weight = 5
    [[menu.footer]]
    parent = "documentation"
    name = "Risk Warnings"
    URL = "/risk-warnings"
    weight = 6

